### ISSUE TITLE
No root password provided

### ISSUE THREAD

**Issue by johnea** [nasa/CFS-101#18]
Hello,
I'm installing and running this CFS-101 VM for the first time, 2022-06-29.

I would like to enable more VirtualBox host OS integration, such as copy buffer sharing.
When attempting to install the VirtualBox guest additions, root password is required.
I find no documentation of the root password, and the "dev" user is not in a sudo configuration that allows sudo to root.

Can you please provide the root password for this VM?

I am also a little concerned with the state of development of the cFS public project in general.
This VM was accessed since attempting to build directly from the OpenSatKit github page yielded dependency requirements that are somewhat obsolete. (Ruby)

Are the cFS and OpenSatKit projects still in active maintenance?

Thank you for your followup!!!

John A
2022-06-29

**Comment by skliper** [comment]
Maybe @tngo67 can answer the root password question?

cFS is active from a general sense (we are working to close out the Draco development cycle now), but not all modules are actively updated based on their distributed ownership and management. See https://github.com/nasa/cFS#other-cfs-related-elementstoolsappsdistributions for related links. I can't speak for OpenSatKit since it's historically been maintained by @dmccomas.

**Comment by johnea** [comment]
Thanks so much for your reply @skliper!

I'm glad to hear the cFS project is still active. We're planning to use it for operational FSW as well as ground testing.

Looking forward to the upcoming Draco release!

**Comment by tngo67** [comment]
This issue has been raised almost as soon as we put this training on github.  We can't provide root password due to an IT security policy.  They want to ensure the VM is only used strictly for the purpose of this training, and nothing else.  Sorry.

**Comment by johnea** [comment]
Thank you for your reply @tngo67!
It is helpful to understand the reasoning at least.
I'll mark this as resolved...
John A
2022-07-12
